const STORAGE_KEY = 'bsom_demo_v1'

function daysAgo(n) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString().slice(0, 10)
}

function tsAgo(days, hours = 0) {
  const d = new Date()
  d.setDate(d.getDate() - days)
  d.setHours(d.getHours() - hours)
  return d.toISOString()
}

// All names, phone numbers, and emails are entirely fictional for demo purposes.
const REFERRALS = [
  {
    id: 'ref-001',
    first_name: 'Kai',
    last_name: 'Okonkwo',
    dob: '2019-03-15',
    caregiver: 'Grace Okonkwo',
    caregiver_phone: '(601) 555-0101',
    caregiver_email: 'gokonkwo@demoemail.com',
    office: 'MERIDIAN',
    insurance: 'Medicaid of MS',
    secondary_insurance: '',
    date_received: daysAgo(45),
    status: 'active',
    current_stage: 'PA Submitted',
    ready_for_parent_interview: false,
    referral_form: 'Completed',
    permission_assessment: 'Completed',
    vineland: 'Completed',
    srs2: 'Completed',
    attends_school: 'YES',
    iep_report: 'Completed',
    insurance_verified: 'YES',
    autism_diagnosis: 'Received',
    intake_paperwork: 'Completed',
    intake_personnel: 'Jordan M.',
    referral_source: 'Ridgeland Pediatric Clinic',
    referral_source_phone: '(601) 555-0200',
    referral_source_fax: '',
    provider_npi: '1234567890',
    point_of_contact: 'Dr. Reeves',
    reason_for_referral: 'ASD diagnosis, seeking ABA therapy services',
    notes: 'Parent very engaged. Insurance pre-authorization in progress.',
    contact1: daysAgo(40),
    contact2: daysAgo(30),
    contact3: daysAgo(20),
    created_at: tsAgo(45),
  },
  {
    id: 'ref-002',
    first_name: 'Priya',
    last_name: 'Nakamura',
    dob: '2020-07-22',
    caregiver: 'Dev Nakamura',
    caregiver_phone: '(601) 555-0202',
    caregiver_email: 'dnakamura@demoemail.com',
    office: 'FOREST',
    insurance: 'UHC Community',
    secondary_insurance: '',
    date_received: daysAgo(22),
    status: 'active',
    current_stage: 'Initial Assessment',
    ready_for_parent_interview: true,
    referral_form: 'Completed',
    permission_assessment: 'Completed',
    vineland: 'Awaiting',
    srs2: 'Awaiting',
    attends_school: 'YES',
    iep_report: 'Emailed',
    insurance_verified: 'YES',
    autism_diagnosis: 'Received',
    intake_paperwork: 'Emailed',
    intake_personnel: 'Taylor R.',
    referral_source: 'Newton County School District',
    referral_source_phone: '(601) 555-0303',
    referral_source_fax: '',
    provider_npi: '',
    point_of_contact: 'Ms. Hargrove (Counselor)',
    reason_for_referral: 'Behavioral challenges in classroom, ASD evaluation recommended',
    notes: 'School provided IEP. Parent interview needs to be scheduled.',
    contact1: daysAgo(18),
    contact2: daysAgo(10),
    contact3: '',
    created_at: tsAgo(22),
  },
  {
    id: 'ref-003',
    first_name: 'Finn',
    last_name: 'Castellano',
    dob: '2018-06-05',
    caregiver: 'Claire Castellano',
    caregiver_phone: '(228) 555-0303',
    caregiver_email: 'ccastellano@demoemail.com',
    office: 'FLOWOOD',
    insurance: 'Magnolia',
    secondary_insurance: '',
    date_received: daysAgo(5),
    status: 'active',
    current_stage: 'New Referral',
    ready_for_parent_interview: false,
    referral_form: 'Awaiting',
    permission_assessment: 'Please Send',
    vineland: 'Awaiting',
    srs2: 'Awaiting',
    attends_school: 'AWAITING',
    iep_report: 'Awaiting',
    insurance_verified: 'AWAITING',
    autism_diagnosis: 'Requested',
    intake_paperwork: 'Please Send',
    intake_personnel: 'Casey L.',
    referral_source: 'Rankin County Early Intervention',
    referral_source_phone: '(601) 555-0404',
    referral_source_fax: '(601) 555-0405',
    provider_npi: '9876543210',
    point_of_contact: 'Dr. Fontaine',
    reason_for_referral: 'Developmental delays, autism evaluation requested',
    notes: 'New referral — initial contact made. Awaiting family paperwork.',
    contact1: daysAgo(3),
    contact2: '',
    contact3: '',
    created_at: tsAgo(5),
  },
  {
    id: 'ref-004',
    first_name: 'Zara',
    last_name: 'Obi',
    dob: '2021-02-19',
    caregiver: 'Amara Obi',
    caregiver_phone: '(769) 555-0404',
    caregiver_email: '',
    office: 'MERIDIAN',
    insurance: 'Molina',
    secondary_insurance: '',
    date_received: daysAgo(18),
    status: 'non-responsive',
    current_stage: 'Intake',
    ready_for_parent_interview: false,
    referral_form: 'Completed',
    permission_assessment: 'Emailed',
    vineland: 'Awaiting',
    srs2: 'Awaiting',
    attends_school: 'NO',
    iep_report: 'N/A',
    insurance_verified: 'AWAITING',
    autism_diagnosis: 'Requested',
    intake_paperwork: 'Awaiting',
    intake_personnel: 'Jordan M.',
    referral_source: 'MS Early Steps Program',
    referral_source_phone: '(601) 555-0505',
    referral_source_fax: '',
    provider_npi: '',
    point_of_contact: 'Early Steps Coordinator',
    reason_for_referral: 'Communication delays, ASD screening recommended',
    notes: 'Three contact attempts — no response. Status marked non-responsive.',
    contact1: daysAgo(15),
    contact2: daysAgo(10),
    contact3: daysAgo(5),
    created_at: tsAgo(18),
  },
  {
    id: 'ref-005',
    first_name: 'Leo',
    last_name: 'Beaumont',
    dob: '2017-06-29',
    caregiver: 'Nicole Beaumont',
    caregiver_phone: '(601) 555-0505',
    caregiver_email: 'nbeaumont@demoemail.com',
    office: 'DAY TREATMENT',
    insurance: 'BCBSMS',
    secondary_insurance: '',
    date_received: daysAgo(55),
    status: 'active',
    current_stage: 'PA Approved',
    ready_for_parent_interview: false,
    referral_form: 'Completed',
    permission_assessment: 'Completed',
    vineland: 'Completed',
    srs2: 'Completed',
    attends_school: 'YES',
    iep_report: 'Completed',
    insurance_verified: 'YES',
    autism_diagnosis: 'Received',
    intake_paperwork: 'Completed',
    intake_personnel: 'Morgan T.',
    referral_source: 'Vicksburg Medical Group',
    referral_source_phone: '(601) 555-0606',
    referral_source_fax: '(601) 555-0607',
    provider_npi: '1122334455',
    point_of_contact: 'Dr. Abboud',
    reason_for_referral: 'ASD diagnosis confirmed, day treatment program referral',
    notes: 'PA approved. Ready to begin services. Scheduling intake interview.',
    contact1: daysAgo(50),
    contact2: daysAgo(40),
    contact3: daysAgo(30),
    created_at: tsAgo(55),
  },
]

const ASSESSMENTS = [
  {
    assessment_id: 'assess-01',
    client_name: 'Kai Okonkwo',
    clinic: 'MERIDIAN',
    office: 'MERIDIAN',
    assigned_bcba: 'Dr. A. Fontenot',
    caregiver: 'Grace Okonkwo',
    caregiver_phone: '(601) 555-0101',
    caregiver_email: 'gokonkwo@demoemail.com',
    insurance: 'Medicaid of MS',
    vineland: 'Completed',
    srs2: 'Completed',
    direct_obs: 'Completed',
    parent_interview_status: 'Completed',
    parent_interview_scheduled_date: daysAgo(25),
    parent_interview_completed_date: daysAgo(20),
    assessment_status: 'Completed',
    assessment_started_date: daysAgo(30),
    assessment_completed_date: daysAgo(10),
    treatment_plan_status: 'In Review',
    treatment_plan_started_date: daysAgo(8),
    treatment_plan_completed_date: null,
    authorization_status: 'Pending',
    authorization_submitted_date: daysAgo(5),
    authorization_approved_date: null,
    ready_for_services: false,
    active_client_date: null,
    in_school: 'YES',
    other_services: 'Speech Therapy',
    notes: 'Assessment complete. TX plan under review. PA submitted and pending.',
    created_at: tsAgo(30),
  },
  {
    assessment_id: 'assess-02',
    client_name: 'Leo Beaumont',
    clinic: 'DAY TREATMENT',
    office: 'DAY TREATMENT',
    assigned_bcba: 'Dr. S. Guerrero',
    caregiver: 'Nicole Beaumont',
    caregiver_phone: '(601) 555-0505',
    caregiver_email: 'nbeaumont@demoemail.com',
    insurance: 'BCBSMS',
    vineland: 'Completed',
    srs2: 'Completed',
    direct_obs: 'Completed',
    parent_interview_status: 'Completed',
    parent_interview_scheduled_date: daysAgo(40),
    parent_interview_completed_date: daysAgo(35),
    assessment_status: 'Completed',
    assessment_started_date: daysAgo(45),
    assessment_completed_date: daysAgo(20),
    treatment_plan_status: 'Finalized',
    treatment_plan_started_date: daysAgo(18),
    treatment_plan_completed_date: daysAgo(7),
    authorization_status: 'Approved',
    authorization_submitted_date: daysAgo(15),
    authorization_approved_date: daysAgo(5),
    ready_for_services: true,
    active_client_date: daysAgo(3),
    in_school: 'YES',
    other_services: 'OT, Speech Therapy',
    notes: 'PA approved. Treatment plan finalized. Ready to begin services.',
    created_at: tsAgo(45),
  },
  {
    assessment_id: 'assess-03',
    client_name: 'Priya Nakamura',
    clinic: 'FOREST',
    office: 'FOREST',
    assigned_bcba: 'Ms. B. Delacroix',
    caregiver: 'Dev Nakamura',
    caregiver_phone: '(601) 555-0202',
    caregiver_email: 'dnakamura@demoemail.com',
    insurance: 'UHC Community',
    vineland: 'Completed',
    srs2: 'In Progress',
    direct_obs: 'Awaiting',
    parent_interview_status: 'Scheduled',
    parent_interview_scheduled_date: daysAgo(-3),
    parent_interview_completed_date: null,
    assessment_status: 'In Progress',
    assessment_started_date: daysAgo(10),
    assessment_completed_date: null,
    treatment_plan_status: 'Not Started',
    treatment_plan_started_date: null,
    treatment_plan_completed_date: null,
    authorization_status: 'Not Submitted',
    authorization_submitted_date: null,
    authorization_approved_date: null,
    ready_for_services: false,
    active_client_date: null,
    in_school: 'YES',
    other_services: '',
    notes: 'Parent interview scheduled. SRS-2 in progress. Awaiting direct obs.',
    created_at: tsAgo(10),
  },
]

const ACTIVITY_LOGS = [
  {
    id: 'log-001',
    action: 'referral_created',
    entity_type: 'referral',
    entity_id: 'ref-001',
    client_name: 'Kai Okonkwo',
    description: 'Kai Okonkwo was added to the intake pipeline.',
    office: 'MERIDIAN',
    actor: 'Jordan M. (Intake Coordinator)',
    metadata: { office: 'MERIDIAN', insurance: 'Medicaid of MS' },
    created_at: tsAgo(45),
  },
  {
    id: 'log-002',
    action: 'insurance_verified',
    entity_type: 'referral',
    entity_id: 'ref-001',
    client_name: 'Kai Okonkwo',
    description: 'Kai Okonkwo insurance verified — updated to YES.',
    office: 'MERIDIAN',
    actor: 'Taylor R. (Intake Coordinator)',
    metadata: { insurance_verified: 'YES' },
    created_at: tsAgo(30),
  },
  {
    id: 'log-003',
    action: 'assessment_updated',
    entity_type: 'assessment',
    entity_id: 'assess-02',
    client_name: 'Leo Beaumont',
    description: 'Leo Beaumont PA authorization was approved.',
    office: 'DAY TREATMENT',
    actor: 'Morgan T. (Intake Coordinator)',
    metadata: { authorization_status: 'Approved' },
    created_at: tsAgo(5),
  },
]

export function getInitialData() {
  return {
    referrals: JSON.parse(JSON.stringify(REFERRALS)),
    assessments: JSON.parse(JSON.stringify(ASSESSMENTS)),
    activityLogs: JSON.parse(JSON.stringify(ACTIVITY_LOGS)),
  }
}

export function loadDemoData() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) return JSON.parse(raw)
  } catch {}
  return null
}

export function saveDemoData(data) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data))
  } catch {}
}

export function resetDemoData() {
  localStorage.removeItem(STORAGE_KEY)
  localStorage.removeItem('bsom_tour_seen')
  window.location.reload()
}
